export const TOGGLE_LOADER = 'TOGGLE_LOADER';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const STORE_USERS = 'STORE_USERS';
export const FILTER_USERS = 'FILTER_USERS';

